# Generated by Django 5.1.7 on 2025-04-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vieweditem',
            options={},
        ),
        migrations.RenameField(
            model_name='vieweditem',
            old_name='timestamp',
            new_name='viewed_at',
        ),
    ]
